### ISSUE TITLE
Wrong picture for ATC SCM19v1

### ISSUE THREAD

**Issue by extreme-sysadminning** [pierreaubert/spinorama#222]
A wrong picture for the ATC SCM19v1 is used.
The picture is a v2, it has a different woofer, enclosure, tweeter and network.

Wrong:
[spinorama](https://github.com/pierreaubert/spinorama)/[datas](https://github.com/pierreaubert/spinorama/tree/master/datas)/[pictures](https://github.com/pierreaubert/spinorama/tree/master/datas/pictures)/ATC SCM19 v1.png

This is the correct ATC SCMv1:
![atc_scm19v1](https://user-images.githubusercontent.com/5648464/210910140-962381b5-cdfd-4a15-bad4-c05a3fbb4beb.jpg)

**Comment by pierreaubert** [comment]
Thanks 
I have changed the picture.
