### ISSUE TITLE
Please make the Ranking sortable.

### ISSUE THREAD

**Issue by staticV3** [pierreaubert/spinorama#229]
**Is your feature request related to a problem? Please describe.**
Having the Ranking list sortable would aid usability greatly.

**Describe the solution you'd like**
Clicking on these headers should sort the list by that attribute. One click -> Ascending, click again -> Descending

-Brand Model
-3dB (Hz)
-Deviation
-Default Score
-Score w/sub
-Score w/eq
-Score w/both

![Screenshot 2023-01-24 194042](https://user-images.githubusercontent.com/39950625/214381772-f0cd1f88-0b12-4257-89e2-023901cdc9d8.png)

**Comment by pierreaubert** [comment]
Good idea. I am almost there but still some bugs. That should work in the coming days when I have a moment.

**Comment by pierreaubert** [comment]
Hello,

that should be done.

Pierre
