### ISSUE TITLE
When comparing two speakers, unable to toggle specific elements on/off. Only the entire speaker.

### ISSUE THREAD

**Issue by staticV3** [pierreaubert/spinorama#231]
**Describe the bug**
Unlike in the graph view of an individual speaker, you can't turn off specific graph elements like Linear Regression or Band ±3dB in the Compare view. Clicking on then just toggles the entire speaker on/off.

**To Reproduce**
1. Open the Compare tool
2. Choose Graph: Estimated in-room response
3. Click on a graph element like Band ±3dB for one of the two speakers

**Expected behavior**
Clicking on an element like Band±3dB below one of the two speakers should toggle just that element on/off, not the entire speaker.
Clicking on the speaker model should toggle all elements of that speaker on/off

**Screenshots**
https://user-images.githubusercontent.com/39950625/218280115-28ee5435-502d-45e1-a210-77c53c6f25e2.mp4

**Smartphone (please complete the following information):**
 - Device: OnePlus 6T
 - OS: Android 11
 - Browser: Chrome
 - Version: 109.0.5414.118

**Comment by pierreaubert** [comment]
Fixed.

Now, you can:
- double click (hide/show) all measurements for 1 speaker
- single click (hide/show) 1 measurement

**Comment by staticV3** [comment]
Awesome! Thank you so much for the quick fix!
