### ISSUE TITLE
Add Toggle All Functionality to Compare view

### ISSUE THREAD

**Issue by staticV3** [pierreaubert/spinorama#240]
**Is your feature request related to a problem? Please describe.**
When comparing two speakers, I often want to quickly hide all graphs for one speaker, like in the CEA2034 view.
Instead, I have to click on each element in the legend one-by-one (e.g. "On axis", "Listening window", "Early reflections", etc)

**Describe the solution you'd like**
I would like to be able to quickly toggle an entire speaker Hidden/Visible by clicking on its model name in the Legend:
![Screenshot 2023-06-03 at 12 29 55](https://github.com/pierreaubert/spinorama/assets/39950625/f016dd29-7941-4af7-9747-d6fb67604dfa)

**Comment by pierreaubert** [comment]
Hello StaticV3,

it should work out of the box. Just double click instead of a single click.
