### ISSUE TITLE
Neumi BS5 with/without EQ "tilt" is incorrect

### ISSUE THREAD

**Issue by Plompudu** [pierreaubert/spinorama#244]
**Describe the bug**
When looking at the Neumi BS5 in-room-Target "tilt" it's -10db@20kHz instead of the normal tilt

**To Reproduce**
1. Go to https://www.spinorama.org/speakers/Neumi%20BS5/ErinsAudioCorner/index_eac-v2-20211212-ported.html
2. Click on Ref vs EQ
3. Scroll down to Estimated in room

**Expected behavior**
The Target Should be identical for with and without EQ

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 114.0.5735.199 (Offizieller Build) (64-Bit)

**Comment by pierreaubert** [comment]
EQ for flat LW:

```
EQ for Neumi BS5 computed from ErinsAudioCorner data
Preference Score 2.93 with EQ 4.54
Generated from http://github.com/pierreaubert/spinorama/generate_peqs.py v0.23
Dated: 2023-07-07-12:06:04

Preamp: -2.8 dB

Filter  1: ON PK Fc    68 Hz Gain +2.65 dB Q 5.25
Filter  2: ON PK Fc   289 Hz Gain +2.50 dB Q 1.05
Filter  3: ON PK Fc   873 Hz Gain +2.94 dB Q 5.92
Filter  4: ON PK Fc  1180 Hz Gain -2.96 dB Q 2.78
Filter  5: ON PK Fc  1704 Hz Gain +2.30 dB Q 5.59
Filter  6: ON PK Fc  8766 Hz Gain +0.31 dB Q 3.19
Filter  7: ON PK Fc 12662 Hz Gain -1.76 dB Q 2.54
```

**Comment by Plompudu** [comment]
Thanks!

I would prefer the flat on-axis.
Could you do the same for the Sealed Measurement?
