### ISSUE TITLE
Spinorama data missing below 200HZ for Polk L200

### ISSUE THREAD

**Issue by JLGF1** [pierreaubert/spinorama#250]
**Describe the bug**

**To Reproduce**

Compare
Polk L200

**Expected behavior**
Data is plotted but missing below 200HZ

**Screenshots**
![Polk L200 Spinorama missing below 200HZ](https://github.com/pierreaubert/spinorama/assets/64571200/1a7d23a2-1fb6-4ce6-bc03-8a14a73eecfb)

**Desktop (please complete the following information):**
 - Win-11
 All

**Additional context**
![Polk L200 Spinorama missing below 200HZ](https://github.com/pierreaubert/spinorama/assets/64571200/d21cc0c2-47f5-45ed-8fba-0548ea8689b0)

Tried browsers Vivaldi (Chromium), Opera (Chromium), Edge

**Comment by pierreaubert** [comment]
hello,

that’s working as expected since the data itself starts at 200Hz. That’s
often the case with in-room measurements.

do you have an idea on how to make it clear on the graph? possibly a
vertical dotted line at 200Hz?

P.

**Comment by JLGF1** [comment]
Hi Pierre,

Ok.  I've looked at many FR plots on Spinoram.org, but that's the first
model I've seen where data below 200HZ (~Schroeder freq) was missing.  I
thought perhaps it was an anomaly.

Yes, a big vertical red line might help to show that the DB knows that data
is not present and therefore can't be displayed.

Thanks.

**Comment by pierreaubert** [comment]
first design, it doesnt work all the time yet [
![newplot (1)](https://github.com/pierreaubert/spinorama/assets/1709343/49e1bffe-c9a8-4db3-b0f9-65afe8fabb48)
](url)
