### ISSUE TITLE
Easy iPython option to manually generate graphs for one speaker

### ISSUE THREAD

**Issue by ddavidebor** [pierreaubert/spinorama#252]
**Is your feature request related to a problem? Please describe.**
I would like to use your software to plot graphs of the speaker I build. However, I'm having a hard time getting started due to the huge amount of moving parts and dependencies.

**Describe the solution you'd like**
An iPython notebook example that can easily import data in the supported format and generate graphs for one speaker on-the-fly

**Describe alternatives you've considered**
Other softwares (not as capable, ugly plots). Writing it by myself (having a hard time wrapping my head around the project as it's quite large and opinionated towards a web app).

**Comment by pierreaubert** [comment]
Would something like that works?

[tutorial](https://github.com/pierreaubert/spinorama/blob/develop/experimental/easyplot.ipynb)

You can see the results [here](https://github.com/pierreaubert/pierreaubert.github.io/blob/master/blog/tutorial/easyplot/easyplot.pdf)

**Comment by ddavidebor** [comment]
That's great! Could you also point me towards calculating the preference scores?

**Comment by pierreaubert** [comment]
```
from spinorama.compute_scores import speaker_pref_rating
speaker_pref_rating(
    cea2034=df['CEA2034'], 
    pir=df['Estimated In-Room Response'],
    rounded=True
)
```

should give you something like:
```
{'nbd_on_axis': 0.359,
 'nbd_listening_window': 0.321,
 'nbd_sound_power': 0.297,
 'nbd_pred_in_room': 0.282,
 'sm_pred_in_room': 0.876,
 'sm_sound_power': 0.943,
 'pref_score_wsub': 7.97,
 'lfx_hz': 43,
 'lfq': 0.829,
 'pref_score': 5.9,
 'aad_on_axis': 0.454}
```

**Comment by ddavidebor** [comment]
Thank you very much!
