### ISSUE TITLE
"Contour 3D Normalized" graphs have stopped working/no longer load

### ISSUE THREAD

**Issue by staticV3** [pierreaubert/spinorama#255]
**Describe the bug**
The "Contour 3D Normalized" graphs (both horizontal and vertical) no longer load properly.

**To Reproduce**
1. Go to Compare view
2. As Graph, choose "SPL Horizontal Contour 3D Normalized" or "SPL Vertical Contour 3D Normalized"
3. Wait for the graph to load
4. It never loads

**Expected behavior**
The graph should load

**Screenshots**
![Screenshot_20231007-223423_Edge](https://github.com/pierreaubert/spinorama/assets/39950625/4ed98187-54a6-4914-8c76-843d77443338)

**Smartphone (please complete the following information):**
 - Device: Samsung Tab S5e
 - OS: Android 11
 - Browser: Edge
 - Version: 117.0.2045.38

**Additional context**
In case this helps track down the bug, it's been quite a few weeks already since the graphs last loaded properly.

**Comment by pierreaubert** [comment]
Works for me with Edge on Mac, Safari on iPhone, Chrome everywhere. I will try on an Android phone.

**Comment by staticV3** [comment]
The graphs load fine when looking at a single speaker, e.g:
https://www.spinorama.org/speakers/Sigberg%20Audio%20Manta/Sigberg%20Audio/vendor/SPL%20Horizontal%20Contour%20Normalized%203D.html
![Screenshot 2023-10-31 225754](https://github.com/pierreaubert/spinorama/assets/39950625/321cc4a3-8483-4b9b-837f-25a04defcd19)

But the Compare view just returns a bunch of 404s:
https://www.spinorama.org/compare.html?measurement=SPL+Horizontal+Contour+3D+Normalized&version0=vendor&origin0=&speaker0=Sigberg+Audio+Manta&version1=vendor-pattern-80x40&origin1=Vendors-KV2+Audio&speaker1=KV2+Audio+EX12
![Screenshot 2023-10-31 225825](https://github.com/pierreaubert/spinorama/assets/39950625/b96296b8-6e8a-48d1-95e1-7d980a8b8864)

**Comment by pierreaubert** [comment]
bug found. It will be corrected shorly
