### ISSUE TITLE
KEF Blade 2 Meta - Bug in In-Room-Frequency response "with EQ"

### ISSUE THREAD

**Issue by totti1965** [pierreaubert/spinorama#269]
*Bonjour Pierre,

Il doit y avoir un problème avec les données d'Erins pour le Kef Blade 2 Meta !
Jetez un coup d'oeil aux données corrigées !
La correction rend la réponse en fréquence bien pire que sans correction : Il n'y a absolument aucune atténuation des basses fréquences aux hautes fréquences avec la réponse dans la pièce (normalement 4 dB ou 5 dB environ de 100 Hz à 20 kHz !).

Il y a un problème avec la correction suggérée (estimation de la réponse dans la pièce avec correction) !
C'est dommage, parce que c'est la meilleure enceinte passive dans la base de données de [spinorama.org](http://spinorama.org/) jusqu'à présent !
   https://www.spinorama.org/speakers/KEF%20Blade%202%20Meta/ErinsAudioCorner/index_eac.html
   
   Klick on "With EQ"!    Scroll down to "Estimated In-Room Response"

L'erreur ne se produit pas avec les données KEF!

L'erreur ne se produit aussi pas avec les données - click Ref. et non "with EQ"!
Seulemont Erins données et "with EQ"!
Mais les données d'Erins Audio Corner sont normalement de meilleure qualité que celles de l'entreprise!

Desktop:
 - OS: Windows 7
 - Browser chrome
 - Version 124.0.6367.91

**Comment by pierreaubert** [comment]
![filters_eq](https://github.com/pierreaubert/spinorama/assets/1709343/be10d1dd-a036-40aa-b78e-aea5e663d98f)

better? that the first one for a flat LW

**Comment by pierreaubert** [comment]
Score move up a bit with this one

![filters_eq](https://github.com/pierreaubert/spinorama/assets/1709343/5163188b-b862-45f7-8345-d2499be97e27)

**Comment by pierreaubert** [comment]
```
EQ for KEF Blade 2 Meta computed from ErinsAudioCorner data
Preference Score 7.07 with EQ 7.36
Generated from http://github.com/pierreaubert/spinorama/generate_peqs.py v0.26
Dated: 2024-05-12-16:34:30

Preamp: -1.1 dB

Filter  1: ON PK Fc    51 Hz Gain +1.23 dB Q 1.70
Filter  2: ON PK Fc    88 Hz Gain -1.07 dB Q 2.04
Filter  3: ON PK Fc   144 Hz Gain -2.18 dB Q 1.67
Filter  4: ON PK Fc   178 Hz Gain +2.32 dB Q 1.18
Filter  5: ON PK Fc   942 Hz Gain -1.35 dB Q 0.91
Filter  6: ON PK Fc  1642 Hz Gain +1.31 dB Q 1.17
Filter  7: ON PK Fc 14134 Hz Gain +0.88 dB Q 2.17
```

**Comment by pierreaubert** [comment]
![eq_compare](https://github.com/pierreaubert/spinorama/assets/1709343/2d20b452-259e-4239-be08-f947f6849bd3)

**Comment by totti1965** [comment]
Thank you so much!

**Comment by totti1965** [comment]
Thank you for your time and the perfect and in depth answer! 😀
