### ISSUE TITLE
Add Tonality Score with Subwoofer 

### ISSUE THREAD

**Issue by Elk445** [pierreaubert/spinorama#280]
Both on axis and within listening window, such as:

https://docs.google.com/spreadsheets/d/e/2PACX-1vRVN63daR6Ph8lxhCDUEHxWq_gwV0wEjL2Q1KRDA0J4i_eE1JS-JQYSZy7kCQZMKtRnjTOn578fYZPJ/pubhtml

I have found these scores particularly useful. The site above has stopped updating with newer products, unlike yours (Thank you!) which does.

**Comment by pierreaubert** [comment]
Hello,

you should see the 4 scores (computed with and without eq, with and without a perfect suwoofer) in at least 2 places:
- for each speaker in the tab called (Data & EQ) for each speaker. See 
![Uploading image.png…]()
- in the [ranking table](https://www.spinorama.org/scores.html?quality=High&sort=score&count=1000)

**Comment by Elk445** [comment]
Thank you for the links and for answering. Is it possible to addd tonality score with sub within the listening window too?Sent from my iPhoneOn Jul 7, 2024, at 9:47 AM, Pierre Aubert ***@***.***> wrote:﻿
Hello,
you should see the 4 scores (computed with and without eq, with and without a perfect suwoofer) in at least 2 places:

for each speaker in the tab called (Data & EQ) for each speaker. See

in the ranking table

**Comment by pierreaubert** [comment]
The tonality score is computed from all the data (LW included).
Sometimes I have 2 EQs, one that optimise the score and one that optimise for a flat LW. Is that what your are talking about?

**Comment by Elk445** [comment]
Yes, that is what I am talking about and didn’t realize. Thank you for your explanation of the tonality score. A definition is probably on your site (which is wonderful), but I missed it. Sent from my iPhoneOn Jul 7, 2024, at 10:08 AM, Pierre Aubert ***@***.***> wrote:﻿
The tonality score is computed from all the data (LW included).
Sometimes I have 2 EQs, one that optimise the score and one that optimise for a flat LW. Is that what your are talking about?
