### ISSUE TITLE
Add F15 and numerical ERDI / SPDI values

### ISSUE THREAD

**Issue by Odjur** [pierreaubert/spinorama#284]
For the purposes of being able to test the limits of room correction EQ, such as with REW that uses 20 bands, it would be nice to have either F10, F12, or F15 values sortable like the F3 and F6 values are.

Similarly, having a number that represents the ERDI and SPDI measurements in the Data & EQ tab would be easier to compare rather than with just the lines on the graph. I don't know exactly what this number would look like, but something weighted like 75% of its average dB value and 25% of its flatness as an idea.

**Comment by pierreaubert** [comment]
Will work on it in #289
